#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

if [ ! -d $OPENSHIFT_DATA_DIR/wordpress ]; then
	mkdir $OPENSHIFT_DATA_DIR/wordpress
fi

if [ ! ls -A $OPENSHIFT_DATA_DIR/wordpress ]; then
    (cd $OPENSHIFT_DATA_DIR/wordpress;wget http://wordpress.org/latest.tar.gz;tar xfz $OPENSHIFT_DATA_DIR/wordpress/latest.tar.gz;mv $OPENSHIFT_DATA_DIR/wordpress/wordpress/* $OPENSHIFT_DATA_DIR/wordpress/;rmdir $OPENSHIFT_DATA_DIR/wordpress/wordpress/;rm -f $OPENSHIFT_DATA_DIR/wordpress/latest.tar.gz)
fi

cp -f $OPENSHIFT_REPO_DIR/.openshift/wp-config.php $OPENSHIFT_DATA_DIR/wordpress/wp-config.php
ln -sf $OPENSHIFT_DATA_DIR/wordpress $OPENSHIFT_REPO_DIR/php/