#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

if [ ! -d $OPENSHIFT_DATA_DIR/wordpress ]; then
	mkdir $OPENSHIFT_DATA_DIR/wordpress
	(cd $OPENSHIFT_DATA_DIR/wordpress;wget http://wordpress.org/latest.tar.gz;tar xfz $OPENSHIFT_DATA_DIR/wordpress/latest.tar.gz;mv $OPENSHIFT_DATA_DIR/wordpress/wordpress/* $OPENSHIFT_DATA_DIR/wordpress/;rmdir $OPENSHIFT_DATA_DIR/wordpress/wordpress/;rm -f $OPENSHIFT_DATA_DIR/wordpress/latest.tar.gz)
fi

cp -f $OPENSHIFT_REPO_DIR/.openshift/wp-config.php $OPENSHIFT_DATA_DIR/wordpress/wp-config.php
ln -sf $OPENSHIFT_DATA_DIR/wordpress/* $OPENSHIFT_REPO_DIR/php/

set -e

if [ -z $OPENSHIFT_MYSQL_DB_HOST ]
then
	echo 1>&2
	echo "Could not find mysql database.  Please run:" 1>&2
	echo "rhc app cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.1" 1>&2
	echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
	echo 1>&2
	exit 5
fi